{
 "title": "Core View",
 "description": "Speed, RPM, Gear and DRS status of your race.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Speed + RPM",
   "type": "timeseries",
   "description": "Speed and RPM graphic of your race",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "f1",
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  speed_kph,\r\n  rpm\r\nFROM telemetry_stream\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts;\r\n"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "timeseries",
   "description": "Gear changes of your race",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "f1",
     "rawSql": "SELECT DISTINCT ON (bucket)\r\n  bucket AS \"time\",\r\n  gear::int AS gear\r\nFROM (\r\n  SELECT\r\n    $__timeGroup(ts, '200ms') AS bucket,\r\n    ts,\r\n    gear\r\n  FROM telemetry_stream\r\n  WHERE $__timeFilter(ts)\r\n) s\r\nORDER BY bucket, ts DESC;\r\n"
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "timeseries",
   "description": "Throttle and brake information of your race",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "f1",
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  throttle,\r\n  brake\r\nFROM telemetry_stream\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts;\r\n"
    }
   ]
  }
 ]
}